/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package blog.api.ktor

import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun createServer() {
    embeddedServer(Netty, port = 3000) {
        routing {
            get("/") {
                call.respondText("Hello, Ktor!")
            }
        }
    }.start(wait = true)
}

fun main() {
    createServer()
}
