ktor:
  deployment:
    port: 3000
    connectionGroupSize: 2
    workerGroupSize: 5
    callGroupSize: 10
    shutdownGracePeriod: 2000
    shutdownTimeout: 3000
    development: true
  application:
    modules:
      - blog.api.ktor.AppKt.module