/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package blog.api.ktor

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val test = "hello"
        assertNotNull(test, "hello")
    }
}
